package createment.oop.answers.part_11_exceptions.exercise_11_1_throw_exception;

public class App {

    public static void main(String[] args) {

    }

}
